on:
  push:
    branches: [ "stage" ]
  pull_request:
    branches: [ "stage" ]

jobs:

  deploy:
    runs-on: ubuntu-latest
    environment: main
    steps:
    - uses: actions/checkout@v3
    - name: SSH Execute Commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        debug: true
        script: |
          cd ${{ secrets.PROJECT_FOLDER }};
          echo '--- LIST OF FILES ---';
          ls -al;
          echo '--- GIT CHECKOUT ---';
          git checkout stage;
          git pull origin stage;
          echo '--- SETTING UP PROJECT ENVIRONMENT ---';
          cp ../.env .env
          echo '--- DOCKER CONTAINERS STOP AND REBUILD ---';
          docker compose down;
          docker system prune -f;
          docker image prune -f;
          echo '--- RUN DOCKER COMPOSE ---';
          docker compose up --build -d;
          echo '--- RUN SYSTEM PRUNE ---';
          docker image prune -f;
          echo '--- SETUP COMPOSER AND ARTISAN ---';
          docker exec app bash -c "composer install ; php artisan key:generate ; php artisan optimize ; php artisan storage:link ; php artisan migrate --seed ; php artisan vendor:publish --provider="Backpack\CRUD\BackpackServiceProvider" --tag=public --force ; php artisan queue:work ; "
